### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (2,) (128,)

### ISSUE THREAD

**Issue by dankaprog** [cheTech/projectCerberus#1]
Когда программа видит лицо вызывается функция face_recogintion.compare_faces, там и происходит ошибка
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/media/daniil/BACKUP/proj/Программирование/projectCerberus/identifyApi.py", line 62, in identify
    compared_face = face_recognition.compare_faces(self.encodings, face_encoding, tolerance=0.60)
  File "/home/daniil/.local/lib/python3.6/site-packages/face_recognition/api.py", line 222, in compare_faces
    return list(face_distance(known_face_encodings, face_encoding_to_check) <= tolerance)
  File "/home/daniil/.local/lib/python3.6/site-packages/face_recognition/api.py", line 72, in face_distance
    return np.linalg.norm(face_encodings - face_to_compare, axis=1)
ValueError: operands could not be broadcast together with shapes (2,) (128,) 
```
в базе данных значения такого вида
```python
face = face_recognition.load_image_file(photoFile)
encodings = face_recognition.face_encodings(face)[0].tolist()
json.dumps(encodings)
```

**Comment by dankaprog** [comment]
#a3b3db3
